apiVersion: v1
description: A Helm chart for CassKop - the Orange Cassandra Kubernetes operator
name: cassandra-operator
home: https://github.com/Orange-OpenSource/casskop
sources:
  - https://github.com/Orange-OpenSource/casskop
version: 1.1.3
appVersion: 1.1.3-release
maintainers:
  - name: allamand
    email: sebastien.allamand@orange.com
  - name: cscetbon
    email: cscetbon@gmail.com
  - name: jal06
    email: jeanarmel.luce@orange.com
  - name: erdrix
    email: aguitton.ext@orange.com
  - name: fdehay
    email: franck.dehay@orange.com
  - name: PERES-Richard
    email: richardperes.info@gmail.com
keywords:
- operator
- cassandra
- casskop
