project: cassandra-operator
mode: time-travel
straggler: kind-control-plane3
front-runner: kind-control-plane
operator-pod: cassandra-operator
command: /cassandra-operator
timing: after
ce-name: cassandra-test-cluster-dc1-rack1-1
ce-namespace: default
ce-rtype: pod
ce-diff-current: '{"metadata": {"deletionTimestamp": "SONAR-EXIST", "deletionGracePeriodSeconds":
  30}}'
ce-diff-previous: '{}'
ce-etype-current: Updated
ce-etype-previous: Updated
se-name: data-volume-cassandra-test-cluster-dc1-rack1-1
se-namespace: default
se-rtype: persistentvolumeclaim
se-etype: ADDED
description: 'Pause kind-control-plane3 after it processes a default/pod/cassandra-test-cluster-dc1-rack1-1
  event E. E should match the pattern {"metadata": {"deletionTimestamp": "SONAR-EXIST",
  "deletionGracePeriodSeconds": 30}} and the events before E should match {}. And
  restart the controller cassandra-operator after kind-control-plane processes a ADDED
  default/persistentvolumeclaim/data-volume-cassandra-test-cluster-dc1-rack1-1 event.'
