apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-hostpath-slow
  labels:
    app.kubernetes.io/instance: hostpath.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-hostpath-slow
    app.kubernetes.io/component: storageclass
provisioner: hostpath.csi.k8s.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  kind: slow
